### ISSUE TITLE
Grammar for Germline variant calling

### ISSUE THREAD

**Issue by kokyriakidis** [varlociraptor/varlociraptor#107]
Hi @johanneskoester ! 

Can you recommend a grammar for Germline variant calling?

**Comment by dlaehnemann** [comment]
How many and what kind of samples do you have per individual? What would be your assumptions about allele frequencies in the different samples?

**Comment by kokyriakidis** [comment]
I want to test Varlociraptor with GIAB datasets. I have 30x Illumina and 30x Hifi data for the 3 GIAB Ashkenazim individuals (HG002, HG003, HG004). I have joint genotyped with DeepVariant and I want to filter the variants detected.

I am not sure how to answear your second question. DeepVariant filters out an allele if its frequency is lower than a certain threshold to avoid calling an erroneous allele. The default is 0.12.

**Comment by dlaehnemann** [comment]
Varlociraptor doesn't do any filtering based on frequencies or any other annotation, but only based on the probabilities computed for the events you define via the grammar scenario:
https://varlociraptor.github.io/docs/filtering/

So optimally, you would give Varlociraptor as many candidate variant sites as possible. So if you can turn off the DeepVariant filtering, you could instead rely on the false discovery rate based filtering. Or generate the candidate variants with some other tool that permits turning off filters, like freebayes for SNVs and smaller variants and delly for bigger indels.  For you setup, you should call candidate variants on all datasets for all individuals jointly. This way, you will catch any site where any dataset has a non-reference allele and will get probabilities that characterize these candidate alleles.

As for calling germline variants: From what I see, [the data you are referring to is a trio](https://jimb.stanford.edu/giab-resources), so you probably want to call germline variants in the son?

So maybe a scenario like this would make sense (@johanneskoester, please feel free to add or correct me on this):
```
samples:
  father:
    resolution: 7
    universe:
      all:  "0.0 | 0.5 | 1.0"
      X: "0.0 | 1.0"
      Y: "0.0 | 1.0"
  mother:
    resolution: 7
    universe:
      all: "0.0 | 0.5 | 1.0"
      Y: "0.0"
  son:
    resolution: 7
    universe: "0.0 | 0.5 | 1.0 | ]0.0,0.5["
      all:  "0.0 | 0.5 | 1.0  | ]0.0,0.5["
      X: "0.0 | 1.0  | ]0.0,1.0["
      Y: "0.0 | 1.0 | ]0.0,1.0["

events:
  germline: "(son:0.5 & (  ( mother:0.0 & !(father:0.0) ) | ( father:0.0 & !(mother:0.0) ) | ( !(mother:0.0) & !(father:0.0) )  )) | (son:1.0 & ( !(mother:0.0) & !(father:0.0) ))"
```
I do hope these parentheses match up! :sweat_smile:

This should:

1. Handle all the different chromosomes correctly (not included in the definition is the mitochondrial sequence, but I'm not sure anybody would know how to define allele frequencies properly there, let alone clearcut germline vs. somatic?).
2. Should exclude somatic variants in the son. I.e. variants with `son:]0.0,0.5[` should not be in somatic, but the complement / rest of allele frequencies event `absent`.
3. `somatic` should portray the different setups of possibly inheriting a variant allele from either parent or both.

Depending on what you are interested in detail, one could also define events like a gemrline homozygous reference genotype separately:
```
  germline_hom_ref: "son:0.0 & !(mother:1.0) & !(father:1.0)"
```

I hope this helps to get the gist of this grammar. And I welcome corrections from its inventor @johanneskoester! :D
