### ISSUE TITLE
free(): invalid next size (fast)

### ISSUE THREAD

**Issue by christopher-schroeder** [varlociraptor/varlociraptor#125]
I get an error by performing BND calling. Varlociraptor version 2.3. I could pin the problem to a specific BND pair:

```
10	81370980	gridss33fb_1085o	T	T[10:81370998[	.	.	EVENT=gridss33fb_1085;SVTYPE=BND;MATEID=gridss33fb_1085h;PROB_MAPPING=2,0,0,0,1,0,6982,48788,1,0,3556,48946;PROB_REF=2,0,0,0,0,0,51712,1,0,29208,48945;PROB_ALT=2,0,0,0,1,0,29415,48945,0,0,52757;PROB_MISSED_ALLELE=2,0,0,0,1,0,29208,49073,1,0,29208,49073;PROB_SAMPLE_ALT=2,0,0,0,1,0,0,32768,1,0,0,32768;PROB_DOUBLE_OVERLAP=2,0,0,0,0,0,64512,0,0,64512;STRAND=2,0,0,0,0,0,1,0;READ_ORIENTATION=2,0,0,0,0,0,0,0;SOFTCLIPPED=257,0,0,0,768,2,0,0,0
10	81370998	gridss33fb_1085h	A	]10:81370980]A	.	.	EVENT=gridss33fb_1085;SVTYPE=BND;MATEID=gridss33fb_1085o;PROB_MAPPING=2,0,0,0,1,0,6982,48788,1,0,3556,48946;PROB_REF=2,0,0,0,0,0,51712,1,0,29208,48945;PROB_ALT=2,0,0,0,1,0,29415,48945,0,0,52757;PROB_MISSED_ALLELE=2,0,0,0,1,0,29208,49073,1,0,29208,49073;PROB_SAMPLE_ALT=2,0,0,0,1,0,0,32768,1,0,0,32768;PROB_DOUBLE_OVERLAP=2,0,0,0,0,0,64512,0,0,64512;STRAND=2,0,0,0,0,0,1,0;READ_ORIENTATION=2,0,0,0,0,0,0,0;SOFTCLIPPED=257,0,0,0,768,2,0,0,0
```

command:
```
varlociraptor call variants generic --scenario scenarios/EPF-BUR.yaml --obs patient13=test/EPF-BUR-012-013.observation.vcf patient28=test/EPF-BUR-012-028.observation.vcf patient29=test/EPF-BUR-012-029.observation.vcf patient31=test/EPF-BUR-012-031.observation.vcf
```

output:
```
free(): invalid next size (fast)
Aborted (core dumped)
```

scenario:
```
samples:
  patient13:
    # male
    resolution: 3
    universe: "0.0 | 0.5 | 1.0"
    X: "0.0 | 1.0"
    Y: "0.0 | 1.0"
  patient28:
    # male
    resolution: 3
    universe: "0.0 | 0.5 | 1.0"
    X: "0.0 | 1.0"
    Y: "0.0 | 1.0"
  patient29:
    # female
    resolution: 3
    universe: "0.0 | 0.5 | 1.0"
    X: "0.0 | 0.5 | 1.0"
    Y: "0.0"
  patient31:
    # female
    resolution: 3
    universe: "0.0 | 0.5 | 1.0"
    X: "0.0 | 0.5 | 1.0"
    Y: "0.0"

events:
  all: "(patient13:0.5 | patient13:1.0) & (patient28:0.5 | patient28:1.0) & (patient29:0.5 | patient29:1.0) & (patient31:0.5 | patient31:1.0)"
  not_interesting: "patient13:0.0 | patient28:0.0 | patient29:0.0 | patient31:0.0"
```

observersions:
[EPF-BUR-012.zip (observation vcfs)](https://github.com/varlociraptor/varlociraptor/files/5336706/EPF-BUR-012.zip)
