### ISSUE TITLE
variant calling grammar complains about `invalid formula` or ``

### ISSUE THREAD

**Issue by dlaehnemann** [varlociraptor/varlociraptor#142]
With this scenario:
```
# This scenario is templated with Jinja2 and rendered for each group (see sample sheet).
# A variable `samples` is available, holding the dataframe of
# the sample sheet, filtered to those samples contained in the group to be rendered.
# For example, this can be used to pass arbitrary column values (like the purity below),
# to the sample definitions.
# Note that sample names here must correspond to the alias column in the sample sheet.

samples:
  germline:
    universe: "[0.0,0.1] | 0.5 | 1.0"
  somatic:
    universe: "[0.0,1.0]"
    contamination:
      by: germline
      fraction: 0.30000000000000004

expressions:
  ffpe_artifact: "(C>T | G>A ) & ( ( somatic:]0.0,0.1] & germline:[0.0,0.1] ) | ( somatic:[0.0,0.1] & germline:]0.0,0.1] ) )"

events:
  ffpe_artifact: "$ffpe_artifact"
  somatic: "germline:0.0 & somatic:]0.0,1.0] & !( $ffpe_artifact )"
  germline: "( germline:]0.0,0.1] | germline:0.5 | germline:1.0 ) & !( $ffpe_artifact )"
```
I get an error:
```
Error: events.somatic: invalid value: invalid VAF formula, expected a valid VAF formula (see https://varlociraptor.github.io/docs/calling) at line 22 column 12
```

I was wondering if it has to do with the use of expressions, and if I inline the expression directly for somatic and germline, i.e.:
```
# This scenario is templated with Jinja2 and rendered for each group (see sample sheet).
# A variable `samples` is available, holding the dataframe of
# the sample sheet, filtered to those samples contained in the group to be rendered.
# For example, this can be used to pass arbitrary column values (like the purity below),
# to the sample definitions.
# Note that sample names here must correspond to the alias column in the sample sheet.

samples:
  germline:
    universe: "[0.0,0.1] | 0.5 | 1.0"
  somatic:
    universe: "[0.0,1.0]"
    contamination:
      by: germline
      fraction: 0.8

expressions:
  ffpe_artifact: "(C>T | G>A ) & ( ( somatic:]0.0,0.1] & germline:[0.0,0.1] ) | ( somatic:[0.0,0.1] & germline:]0.0,0.1] ) )"

events:
  ffpe_artifact: "$ffpe_artifact"
#  somatic: "germline:0.0 & somatic:]0.0,1.0] & !( $ffpe_artifact )"
#  germline: "( germline:]0.0,0.1] | germline:0.5 | germline:1.0 ) & !( $ffpe_artifact )"
  somatic: "germline:0.0 & somatic:]0.0,1.0] & !( (C>T | G>A ) & ( ( somatic:]0.0,0.1] & germline:[0.0,0.1] ) | ( somatic:[0.0,0.1] & germline:]0.0,0.1] ) ) )"
  germline: "( germline:]0.0,0.1] | germline:0.5 | germline:1.0 ) & !( (C>T | G>A ) & ( ( somatic:]0.0,0.1] & germline:[0.0,0.1] ) | ( somatic:[0.0,0.1] & germline:]0.0,0.1] ) ) )"
```
Then, I get a different error:
```
thread 'main' panicked at 'bug: observable_max may not be called if end=0.0.', src/grammar/formula.rs:381:9
```

I have also tried with `germline:[0.0,0.0]` instead of `germline:0.0`, but this does not change the error. It sounds like this is a corner case that is not yet implemented?

**Comment by dlaehnemann** [comment]
This should be resolved.

**Comment by bwubb** [comment]
Hello,
  I am receiving this message in version 4.11.4.

I basically copied the example ffpe artifact handling and merged it with tumor/normal events. I do not understand what was the resolution to this issue? Do I need to construction the expression differently?

My scenation looks as:
```
samples:
  normal:
    resolution: 0.1
    universe: "0.0 | 0.5 | 1.0 | ]0.0,0.5["
  tumor:
    resolution: 0.01
    universe: "[0.0,1.0]"
    contamination:
      by: normal
      fraction: 0.0

expressions:
  ffpe_subst: "(C>T | G>A)"

events:
  ffpe_artifact:
    "$ffpe_subst & tumor:]0.0,0.05["
  present:
    "($ffpe_subst & tumor:]0.05,1.0]) | (!$ffpe_subst & tumor:]0.0,1.0[)"
  germline:
    "normal:0.5 | normal:1.0"
  somatic_normal:
    "normal:]0.0,0.5["
  somatic_tumor:
    "normal:0.0 & tumor:]0.0,1.0]"
```

Which gives me:

```
varlociraptor call variants generic --scenario ffpe_scenario.yml --obs tumor=PP002-DZ3A.observations.bcf normal=PP002-DB1B.observations.bcf > PP002-DZ3A.ffpe_scenario.bcf
Error: expressions.ffpe_subst: invalid value: invalid VAF formula:
 --> 1:2
  |
1 | (C>T | G>A)
  |  ^---
  |
  = expected conjunction, expected a valid VAF formula (see https://varlociraptor.github.io/docs/calling) at line 13 column 15

```

Perhaps my grammar is not correct in some way?

Thank you.

**Comment by bwubb** [comment]
It looks like I have it working when I added the VAF condidtions to ffpe_subst expression, and removed "present" event. I think this confuses me on how to properly use events vs expressions.

```
samples:
  normal:
    resolution: 0.1
    universe: "0.0 | 0.5 | 1.0 | ]0.0,0.5["
  tumor:
    resolution: 0.01
    universe: "[0.0,1.0]"
    contamination:
      by: normal
      fraction: 0.35

expressions:
  ffpe_subst: "(C>T | G>A) & ((tumor:]0.0,0.1] & normal:[0.0,0.1]) | (tumor:[0.0,0.1] & normal:]0.0,0.1]))"

events:
  ffpe_artifact:
    "$ffpe_subst"
  #present:
  #  "($ffpe_subst & tumor:]0.05,1.0]) | (!$ffpe_subst & tumor:]0.0,1.0[)"
  germline:
    "normal:0.5 | normal:1.0"
  somatic_normal:
    "normal:]0.0,0.5["
  somatic_tumor:
    "normal:0.0 & tumor:]0.0,1.0]"
```
Does this properly compare an ffpe_artifact vs true somatic_tumor?

**Comment by dlaehnemann** [comment]
Thanks for reporting, that [the FFPE example in the scenario catalog](https://varlociraptor.github.io/varlociraptor-scenarios/scenarios/ffpe-artifact-handling/) does not work in the current version. I guess this is due to some check for a valid expression that was introduced during some bug fixes after this example was originally included. We'll see whether to update the check or the example accordingly.

In the example, the idea of the `present` event is to actually represent genuine variation, only `ffpe_artifact` is supposed to represent the FFPE event. Thus, putting `present` into `ffpe_artifact` mixes two things. I completely agree that the whole idea of a multi-dimensional allele frequency space can be very confusing, especially when further mixed with the substitution types. So this does take me a moment to wrap my head around, as well, and it is important that the full multi-dimensional allele frequency space is defined into events (uniquely). :

```
expressions:
  ffpe:
    # an artifact can appear in either the tumor or the normal sample, but as these are random, probably
    # not in both at the exact same position -- also, we assume a maximum artifact frequency of 0.1, as
    # opposed to the 0.05 in the scenario catalog example
    "(C>T | G>A) & ((tumor:0.0 & normal:]0.0,0.1]) | (tumor:]0.0,0.1] & normal:0.0))"

events:
  ffpe_artifact: "$ffpe"
  germline:
    # this implies any frequency (and any substitution) for the tumor (i.e. "tumor:[0.0,1.0] & ()")
    "normal:0.5 | normal:1.0"
  somatic_normal:
    # tumor frequency implication as for germline, but here the allele frequency space overlaps
    # with that of the `ffpe_artifact` event / `$ffpe` expression -- so we have to exclude that bit
    # of allele frequency space explicitly, to avoid counting it twice (towards this event and towards
    # `ffpe_artifact` above)
    "normal]0.0,0.5[ & !$ffpe"
  somatic_tumor:
    # as in `somatic_normal`, the allele frequency space would overlap with the `ffpe_artifact`
    # event, here at "(C>T | G>A) & normal:0.0 & tumor:]0.0,0.1]", so we explicitly exclude the
    # `$ffpe` expression again
    "normal:0.0 & tumor:]0.0,1.0] & !$ffpe"
```

I hope, this helps?

Should this event definition not work currently, due to the syntax issue, just paste the expression into every place where it occurs, for now---even if this means some redundancy, this should get it to work.
