### ISSUE TITLE
Questions:  Improving PROB_GERMLINE for better FDR filtering.

### ISSUE THREAD

**Issue by bwubb** [varlociraptor/varlociraptor#424]
Greetings,

  I have a paired somatic pipeline and two of the callers it uses are vardict and varscan2, which will output germline calls as well. I wanted to include them into my VLR candidates because I figure it would distinguish them as PROB_GERMLINE and I could select and filter for that even in a separate output bcf. Most of our tumor/normal pairs have some sort of known inherent variant and we want to observe its presence and allele frequency in the tumor variant calling (usually for loh purposes).

My scenario grammar looks like: (contamination fraction is filled accurately for each sample pair)
```
samples:
  normal:
    resolution: 0.1
    universe: "0.0 | 0.5 | 1.0 | ]0.0,0.5["
  tumor:
    resolution: 0.01
    universe: "[0.0,1.0]"
    contamination:
      by: normal
      fraction: 0.0

expressions:
  ffpe: '(C>T | G>A) & ((tumor:0.0 & normal:]0.0,0.1]) | (tumor:]0.0,0.1] & normal:0.0))'

events:
  ffpe_artifact:
    '$ffpe'
  germline:
    'normal:0.5 | normal:1.0'
  somatic_normal:
    'normal:]0.0,0.5['
  somatic_tumor:
    'normal:0.0 & tumor:]0.0,1.0] & !$ffpe'
```

When it comes to the FDR filtering value I need to set it very high (~0.2-0.3) in order to capture these known germline variants in the output for PROB_GERMLINE. Ive repeated this in two separate datasets/tumor types each with ~50 pairs at least. When I look at the probability values at these known variant sites, PROB_GERMLINE is the the lowest value among all the  evaluated events, but the values themselves seems very high. 

I guess because they are "known to be real" and have good coverage I was expecting the model to be more confident and I could drop the FDR value down to 0.05. I am trying to understand if my grammar could be improved? Is VLR less suited for making GERMLINE calls in tumor/normal pairs? Maybe I am misunderstanding something else. Thank you

-bwubb
